### ISSUE TITLE
Update Application to have details on using TCP/IP and iAP2

### ISSUE THREAD

**Issue by asm09fsu** [smartdevicelink/hello_sdl_ios#1]
Currently, this application has no code or explanation on how to connect to core in a vehicle (via iAP2) and to an emulator (via Wifi).

**Comment by baymak** [comment]
I have  the same problem. Impossible to see the app on Sync3 or ALE emulator and don't know where to look at???

**Comment by asm09fsu** [comment]
Resolved in [v1.0.0](https://github.com/smartdevicelink/hello_sdl_ios/releases/tag/v1.0.0)
