### ISSUE TITLE
Example not using latest syntax

### ISSUE THREAD

**Issue by JamaicanRumCream** [smartdevicelink/hello_sdl_ios#10]
This example is still using pre- 4.3.x code. There is no SDLManager, it still has SDLProxy etc. (The master branch)

**Comment by asm09fsu** [comment]
@JamaicanRumCream please use develop. Due to the fact that we support Swift and Objective-C, develop is up to date with 4.5.2 and `feature/swift-3.0` has support for Swift 3 and SDL 4.5.2
