### ISSUE TITLE
compile error in feature/swift branch - method onOnLockScreenNotification conflicts with optional requirement method

### ISSUE THREAD

**Issue by troyibm** [smartdevicelink/hello_sdl_ios#7]
I realized that there's no reason I should think the feature/swift branch would work, but I thought it would be worth a try.  I get this compile error when I try to build with Xcode 7.3.1.  Maybe someone could fix before the CITA ford hackathon so we can use this swift example to start from.  Thanks.

Here's the error:  I tried to fix, but I don't understand the problem.

HSDLProxyManager.swift:312:10: Objective-C method 'onOnLockScreenNotification:' provided by method 'onOnLockScreenNotification' conflicts with optional requirement method 'onOnLockScreenNotification' in protocol 'SDLProxyListener'

/cc @asm09fsu

**Comment by troyibm** [comment]
line 312 of HSDLProxyManager.swift should be:
    @objc func onOnLockScreenNotification(notification: SDLOnLockScreenStatus?) {

SDLOnLockScreenStatus instead of SDLLockScreenStatus

**Comment by asm09fsu** [comment]
Fixed in commit [cc01013](https://github.com/smartdevicelink/hello_sdl_ios/commit/cc01013070a26ba2e21ad4ed9e382fa03d3c1f61)
