### ISSUE TITLE
Unable to find a specification for `SmartDeviceLink-iOS (~> 4.2.3)`

### ISSUE THREAD

**Issue by ianchild** [smartdevicelink/hello_sdl_ios#9]
Unable to find a specification for `SmartDeviceLink-iOS (~> 4.2.3)`

**Comment by joeljfischer** [comment]
@ianchild Please try the following command in your terminal:
`pod repo update` then try again. I've confirmed this specification exists.

**Comment by asm09fsu** [comment]
Closing as this is resolved.
